[project]
name = "themost_framework"
version = "1.0.1"
authors = [
  { name="Kyriakos Barbounakis", email="k.barbounakis@gmail.com" },
]
description = "@themost-framework for python"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: BSD-3-Clause",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/themost-framework/themost-framework-py"
"Bug Tracker" = "https://github.com/pypa/themost-framework/themost-framework-py/issues"